// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (uuid.UUID, error)
	GetArticleById(ctx context.Context, id uuid.UUID) (Article, error)
	GetArticles(ctx context.Context) ([]Article, error)
}

var _ Querier = (*Queries)(nil)
